### ISSUE TITLE
qbench2 question 55 sparql exception

### ISSUE THREAD

**Issue by KonradHoeffner** [AKSW/cubeqa#33]
Question Number 55: Answering How much did Armenia spent in 2009 on general public services?
correct query: select sum(xsd:decimal(?amount)) as ?sum from <http://linkedspending.aksw.org/618ac3ec98384f44a9ef142356ce476d>
{
?obs qb:dataSet ls:618ac3ec98384f44a9ef142356ce476d.
?obs lso:618ac3ec98384f44a9ef142356ce476d-cofog1 <https://openspending.org/618ac3ec98384f44a9ef142356ce476d/cofog1/01>.
?obs lso:618ac3ec98384f44a9ef142356ce476d-amount ?amount.
?obs lso:refYear ?year.
filter(year(?year)=2009).
}
correct answer: [{=113006558300}]
no range: creating NOP property scorer for http://linkedspending.aksw.org/ontology/cofog1
no range: creating NOP property scorer for http://linkedspending.aksw.org/ontology/cofog3
no range: creating NOP property scorer for http://linkedspending.aksw.org/ontology/cofog2
no range: creating NOP property scorer for http://linkedspending.aksw.org/ontology/economic
range http://linkedspending.aksw.org/ontology/fromClass unknown: creating NOP scorer for http://linkedspending.aksw.org/ontology/from
no range: creating NOP property scorer for http://linkedspending.aksw.org/ontology/economicidlevel2
no range: creating NOP property scorer for http://linkedspending.aksw.org/ontology/cofog
no range: creating NOP property scorer for http://linkedspending.aksw.org/ontology/economiclevel3
no range: creating NOP property scorer for http://linkedspending.aksw.org/ontology/datasetid
no range: creating NOP property scorer for http://linkedspending.aksw.org/ontology/economiclevel2
no range: creating NOP property scorer for http://linkedspending.aksw.org/ontology/economiclevel1
no range: creating NOP property scorer for http://linkedspending.aksw.org/ontology/economicidlevel1
no range: creating NOP property scorer for http://linkedspending.aksw.org/ontology/type
no range: creating NOP property scorer for http://linkedspending.aksw.org/ontology/program
no range: creating NOP property scorer for http://linkedspending.aksw.org/ontology/economicidlevel3
Exception in thread "main" java.lang.RuntimeException: error with sparql query select ?p {?spec ?p <http://linkedspending.aksw.org/ontology/618ac3ec98384f44a9ef142356ce476d-amount>. filter(contains(str(?p),"http://purl.org/linked-data/cube#"))} limit 1
	at org.aksw.cubeqa.property.ComponentProperty.<init>(ComponentProperty.java:111)
	at org.aksw.cubeqa.property.ComponentProperty.getInstance(ComponentProperty.java:201)
	at org.aksw.cubeqa.Cube.getDefaultAnswerProperty(Cube.java:172)
	at org.aksw.cubeqa.template.CubeTemplateFragment.toTemplate(CubeTemplateFragment.java:157)
	at org.aksw.cubeqa.template.CubeTemplator.buildTemplate(CubeTemplator.java:52)
	at org.aksw.cubeqa.Algorithm.answer(Algorithm.java:14)
	at org.aksw.cubeqa.benchmark.Benchmark.evaluate(Benchmark.java:128)
	at org.aksw.cubeqa.benchmark.Benchmark.evaluate(Benchmark.java:105)
	at org.aksw.cubeqa.scripts.EvaluateQBench2.main(EvaluateQBench2.java:14)
Caused by: java.util.NoSuchElementException: QueryIterPlainWrapper
	at com.hp.hpl.jena.sparql.engine.iterator.QueryIteratorBase.nextBinding(QueryIteratorBase.java:152)
	at com.hp.hpl.jena.sparql.engine.iterator.QueryIteratorBase.next(QueryIteratorBase.java:129)
	at com.hp.hpl.jena.sparql.engine.iterator.QueryIteratorBase.next(QueryIteratorBase.java:41)
	at com.hp.hpl.jena.sparql.engine.ResultSetStream.nextBinding(ResultSetStream.java:87)
	at com.hp.hpl.jena.sparql.engine.ResultSetStream.nextSolution(ResultSetStream.java:115)
	at com.hp.hpl.jena.sparql.engine.ResultSetStream.next(ResultSetStream.java:124)
	at com.hp.hpl.jena.sparql.engine.ResultSetCheckCondition.next(ResultSetCheckCondition.java:65)
	at org.aksw.cubeqa.property.ComponentProperty.<init>(ComponentProperty.java:110)
	... 8 more

**Comment by KonradHoeffner** [comment]
The dataset was not fully uploaded on the local SPARQL endpoint because the ntriples file was corrupted. Deleting the graph and virtloading a fresh copy of the original ntriples file solved the issue.
